### ISSUE TITLE
Drops

### ISSUE THREAD

**Issue by Voldaric** [Romejanic/4chan-Discord-Bot#13]
There should be a random board drop in every 3 or 5 mins.... This way... Interesting things will come without pressing /random etc thankx 🍀

**Comment by Romejanic** [comment]
Hey, thanks for the suggestion.

The bot already supports this behaviour. You can configure a subscription which automatically sends a random post from the selected board at an interval of your choosing. [Click here](https://github.com/Romejanic/4chan-Discord-Bot/blob/master/CONFIG.md#subscriptions) to learn more.
