### ISSUE TITLE
Automatic Post Interval

### ISSUE THREAD

**Issue by ThePieMonster** [Romejanic/4chan-Discord-Bot#2]
New feature

Setup a option in the config to allow automatic posting of a chosen board every x minutes.

Also add documentation for the "config" options on [GitHub ](https://github.com/Romejanic/4chan-Discord-Bot)and [Top.gg](https://top.gg/bot/592655834568327179)

**Comment by Romejanic** [comment]
Sounds awesome! Thanks for the idea :)

**Comment by Romejanic** [comment]
This was implemented in the latest release
