### ISSUE TITLE
Non-functional on my server.

### ISSUE THREAD

**Issue by IntraVelet** [Romejanic/4chan-Discord-Bot#3]
Not sure if this is a rookie mistake on my part or something bigger.
Reinvited and enabled slash commands (plus any other required permissions) on my server but no functionality present from the bot when using slash commands.
+ prefix still works fine (getting the slash commands migration message when using the prefix) but nothing from the / commands.
Thank you.

**Comment by Romejanic** [comment]
Nope this is my bad, it looks like I need to update the invite link for slash commands to work properly.

[Click here to reinvite it properly](https://discord.com/oauth2/authorize?client_id=592655834568327179&permissions=124992&scope=bot%20applications.commands)

Thanks so much for bringing this to my attention!
